// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using praticeAPI.Data;

#nullable disable

namespace praticeAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.6.23329.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("praticeAPI.Models.Domain.Difficulty", b =>
                {
                    b.Property<Guid?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Difficulties");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8527976b-94ed-4bc8-96f1-e9ade2386882"),
                            Name = "Easy"
                        },
                        new
                        {
                            Id = new Guid("40c7c352-af79-42b6-85aa-cfdf1e4034ac"),
                            Name = "Medium"
                        },
                        new
                        {
                            Id = new Guid("d73209ae-079a-4191-9227-973fd1d398ab"),
                            Name = "Hard"
                        });
                });

            modelBuilder.Entity("praticeAPI.Models.Domain.Image", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("filePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("fileSize")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("images");
                });

            modelBuilder.Entity("praticeAPI.Models.Domain.Region", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ca8ded17-e6a9-475c-9feb-f7792ea7ce83"),
                            Code = "IND",
                            ImageURL = "https://facts.net/wp-content/uploads/2023/06/49-facts-about-india-1688115169.jpeg",
                            Name = "India"
                        },
                        new
                        {
                            Id = new Guid("47f10a09-ca9d-49b9-bb75-26e730e5eb5b"),
                            Code = "USA",
                            ImageURL = "https://d.newsweek.com/en/full/1865970/statue-liberty.jpg",
                            Name = "United States of America"
                        },
                        new
                        {
                            Id = new Guid("72d75104-5c01-4284-83ef-f7e8e78e258c"),
                            Code = "UK",
                            ImageURL = "https://fullsuitcase.com/wp-content/uploads/2021/01/Tower-Bridge-in-London-UK.jpg.webp",
                            Name = "United KingDom"
                        },
                        new
                        {
                            Id = new Guid("3902bdb6-732a-4272-8d1c-562ebf6ae914"),
                            Code = "JP",
                            ImageURL = "https://www.exoticca.com/us/blog/wp-content/uploads/2021/08/Japan-sightseeing-BLOG-header-930x360.png",
                            Name = "Japan"
                        },
                        new
                        {
                            Id = new Guid("1a5b973d-5222-4d5a-8936-9aa8999d1336"),
                            Code = "CN",
                            ImageURL = "https://www.planetware.com/photos-large/CHN/china-great-wall-and-mountain.jpg",
                            Name = "China"
                        },
                        new
                        {
                            Id = new Guid("0ca97531-1fb7-431b-9b11-c13d6b04b8c8"),
                            Code = "PAK",
                            ImageURL = "https://c.tribune.com.pk/2015/12/final-6.jpg",
                            Name = "Pakistan"
                        });
                });

            modelBuilder.Entity("praticeAPI.Models.Domain.Walk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("DifficultyID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("LengthInKM")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RegionID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WalkImageURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DifficultyID");

                    b.HasIndex("RegionID");

                    b.ToTable("Walks");
                });

            modelBuilder.Entity("praticeAPI.Models.Domain.Walk", b =>
                {
                    b.HasOne("praticeAPI.Models.Domain.Difficulty", "Difficulty")
                        .WithMany()
                        .HasForeignKey("DifficultyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("praticeAPI.Models.Domain.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Difficulty");

                    b.Navigation("Region");
                });
#pragma warning restore 612, 618
        }
    }
}
